<?php
namespace Phossa\Route\Collector;

use Phossa\Route\Status;
use Phossa\Route\Context\Result;
use Phossa\Route\Context\Request;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-03-11 at 11:42:56.
 */
class CollectorQPRTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var CollectorQPR
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new CollectorQPR;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * Call protected/private method of a class.
     *
     * @param string $methodName Method name to call
     * @param array  $parameters Array of parameters to pass into method.
     *
     * @return mixed Method return.
     */
    protected function invokeMethod($methodName, array $parameters = [])
    {
        $reflection = new \ReflectionClass($this->object);
        $method = $reflection->getMethod($methodName);
        $method->setAccessible(true);

        return $method->invokeArgs($this->object, $parameters);
    }

    /**
     * getPrivateProperty
     *
     * @param 	string $propertyName
     * @return	the property
     */
    public function getPrivateProperty($propertyName)
    {
        $reflector = new \ReflectionClass($this->object);
        $property = $reflector->getProperty($propertyName);
        $property->setAccessible(true);

        return $property->getValue($this->object);
    }

    /**
     * @covers Phossa\Route\Collector\CollectorQPR::matchRoute
     */
    public function testMatchRoute1()
    {
        $result = new Result(new Request(
            'GET', '/path/?r=controller-action-id-1-name-nick'
        ));
        if ($this->object->matchRoute($result)) {
            $this->assertEquals('1', $result->getParameter('id'));
            $this->assertEquals('nick', $result->getParameter('name'));
            $this->assertEquals(['controller', 'action'], $result->getHandler());
        } else {
            throw new \Exception('bad');
        }
    }

    /**
     * @covers Phossa\Route\Collector\CollectorQPR::matchRoute
     */
    public function testMatchRoute2()
    {
        $result = new Result(new Request(
            'GET', '/path/?r=controller-action-id-name-nick'
        ));
        $this->assertFalse($this->object->matchRoute($result));
        $this->assertEquals(Status::BAD_REQUEST, $result->getStatus());
    }


    /**
     * @covers Phossa\Route\Collector\CollectorQPR::matchRoute
     */
    public function testMatchRoute3()
    {
        $this->object = new CollectorQPR(['varname' => 's', 'seperator' => '/']);
        $result = new Result(new Request(
            'GET', '/path/?s=cont/action/id/1/name/nick'
        ));
        $this->assertTrue($this->object->matchRoute($result));
        $this->assertEquals(['cont', 'action'], $result->getHandler());
    }
}
