<?php
namespace Phossa\Route\Regex;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-03-13 at 18:10:35.
 */
class ParserGcbTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ParserGcb
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ParserGcb;
        $this->pattern = '/blog[/{section:xd}][/{year:d}[/{month:d}[/{date:d}]]]';
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * Call protected/private method of a class.
     *
     * @param string $methodName Method name to call
     * @param array  $parameters Array of parameters to pass into method.
     *
     * @return mixed Method return.
     */
    protected function invokeMethod($methodName, array $parameters = [])
    {
        $reflection = new \ReflectionClass($this->object);
        $method = $reflection->getMethod($methodName);
        $method->setAccessible(true);

        return $method->invokeArgs($this->object, $parameters);
    }

    /**
 	 * getPrivateProperty
 	 *
 	 * @param 	string $propertyName
 	 * @return	the property
 	 */
	public function getPrivateProperty($propertyName) {
		$reflector = new \ReflectionClass($this->object);
		$property  = $reflector->getProperty($propertyName);
		$property->setAccessible(true);

		return $property->getValue($this->object);
	}

    /**
     * @covers Phossa\Route\Regex\ParserGcb::convert
     */
    public function testConvert()
    {
        list(, $map) = $this->invokeMethod('convert', [ $this->pattern ]);
        $this->assertTrue(4 == count($map));
    }

    /**
     * @covers Phossa\Route\Regex\ParserGcb::getMapData
     */
    public function testGetMapData()
    {
        $maps = [
            'a' => [ 'sec', 'name', 'key'],
            'b' => [ 'wow', 'bingo', 'yes'],
            'c' => [ 'yes', 'no' ],
            'd' => [ 'xox', 'yoy'],
            'e' => [ 'test', 'help']
        ];
        $arr  = [
            'a' => 'sdfadfssadfa',
            'b' => 'dssssx',
            'c' => 'ccccccc',
            'd' => 'dfadafadfa',
            'e' => 'sxxxx'
        ];

        $res = $this->invokeMethod('getMapData', [ $arr, $maps ]);
        $this->assertTrue(5 == $res['a']);
        $this->assertTrue(6 == $res['c']);
        $this->assertTrue(7 == $res['d']);
    }

    /**
     * @covers Phossa\Route\Regex\ParserGcb::parse
     * @covers Phossa\Route\Regex\ParserGcb::match
     */
    public function testParse()
    {
        // parse route
        $p1 = '/user[/{name:c}]';
        $p2 = '/blog/{section:xd}[/{year:d}]';
        $p3 = '/news[/{year:d}[/{month:d}[/{date:d}]]]';
        $p4 = '/sport/{name:xd}/{season:xd}';
        $this->object->parse('p1', $p1);
        $this->object->parse('p2', $p2);
        $this->object->parse('p3', $p3);
        $this->object->parse('p4', $p4);

        // match
        $this->assertFalse($this->object->match('/sport/bike'));

        list($r1, $a1) = $this->object->match('/news/2016/12');
        $this->assertTrue('p3' === $r1);
        $this->assertEquals(['year' => '2016', 'month' => '12'], $a1);

        list($r2, $a2) = $this->object->match('/user');
        $this->assertTrue('p1' === $r2);
        $this->assertEquals([], $a2);

        list($r3, $a3) = $this->object->match('/blog/list');
        $this->assertTrue('p2' === $r3);
        $this->assertEquals(['section' => 'list'], $a3);

        list($r4, $a4) = $this->object->match('/user/phossa');
        $this->assertTrue('p1' === $r4);
        $this->assertEquals(['name' => 'phossa'], $a4);
    }
}
